apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: watch
  name: watch
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: watch:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-java11:latest
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers: []
